---
title: "EUResearchHub"
output:
  html_document
---

---

<style>
    body{

    }
    .sub-title{
        font-size:20px;
        font-weight: bold;
    }
    .section-title{
        font-size:15px;
        font-weight: bold;
    }
</style>

<p class="sub-title">Modellazione principale</p>

<p class="section-title" >Ricercatori</p>

I ricercatori devono poter creare nuovi progetti avere accesso ai report di valutazione e rivedere i loro progetti finchè non vengono approvati o rifiutati.

<p class="section-title" >Valutatori</p>

I valutatori possono accedere ai progetti da valutare nella prossima finestra di valutazione, scaricare i documenti da valutare e creare un report di valutazione per ognuno di essi.<br>
Inoltre hanno la facoltà di aggiornare lo stato di un progetto.

<p class="section-title" >Progetti</p>

Ogni progetto comprende una descrizione testuale ed uno o più documenti formato pdf da valutare, possibilmente di tipo diverso (data management plan, ethics deliverable, ...).<br>
I progetti assumono diversi stati, lo stato di default è "sottomesso per valutazione" che comprende tutti quei progetti appena creati che non hanno ancora ricevuto una valutazione.<br>
Altri stati che possono assumere sono: "approvato", "rifiutato" e "richiede modifiche".<br>
Questi tre stati possono essere cambiati solo dai valutatori e una volta approvati o rifiutati non possono più essere modificati.

---

<p class="sub-title">Modellazione secondaria</p>

<p class="section-title" >Versioni</p>

Di ogni progetto si vogliono tenere traccia le diverse iterazioni del processo di valutazione. In particolare, per ogni progetto, ricercatori e valutatori devono poter accedere alle versioni sottomesse precedentemente ed al relativo report di valutazione. <br>
Le versioni possono includere informazioni ausiliarie che descrivano i cambiamenti rispetto alle versioni precedenti.
